// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: humanoid_monitor.proto

#include "humanoid_monitor.pb.h"
#include "humanoid_monitor.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace humanoid_monitor {

static const char* HumanoidMonitorService_method_names[] = {
  "/humanoid_monitor.HumanoidMonitorService/SubscribeState",
  "/humanoid_monitor.HumanoidMonitorService/GetVersion",
};

std::unique_ptr< HumanoidMonitorService::Stub> HumanoidMonitorService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HumanoidMonitorService::Stub> stub(new HumanoidMonitorService::Stub(channel, options));
  return stub;
}

HumanoidMonitorService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_SubscribeState_(HumanoidMonitorService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::SERVER_STREAMING, channel)
  , rpcmethod_GetVersion_(HumanoidMonitorService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::ClientReader< ::humanoid_monitor::SecurityState>* HumanoidMonitorService::Stub::SubscribeStateRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SubscribeStateRequest& request) {
  return ::grpc::internal::ClientReaderFactory< ::humanoid_monitor::SecurityState>::Create(channel_.get(), rpcmethod_SubscribeState_, context, request);
}

void HumanoidMonitorService::Stub::async::SubscribeState(::grpc::ClientContext* context, const ::humanoid_monitor::SubscribeStateRequest* request, ::grpc::ClientReadReactor< ::humanoid_monitor::SecurityState>* reactor) {
  ::grpc::internal::ClientCallbackReaderFactory< ::humanoid_monitor::SecurityState>::Create(stub_->channel_.get(), stub_->rpcmethod_SubscribeState_, context, request, reactor);
}

::grpc::ClientAsyncReader< ::humanoid_monitor::SecurityState>* HumanoidMonitorService::Stub::AsyncSubscribeStateRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SubscribeStateRequest& request, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::humanoid_monitor::SecurityState>::Create(channel_.get(), cq, rpcmethod_SubscribeState_, context, request, true, tag);
}

::grpc::ClientAsyncReader< ::humanoid_monitor::SecurityState>* HumanoidMonitorService::Stub::PrepareAsyncSubscribeStateRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SubscribeStateRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderFactory< ::humanoid_monitor::SecurityState>::Create(channel_.get(), cq, rpcmethod_SubscribeState_, context, request, false, nullptr);
}

::grpc::Status HumanoidMonitorService::Stub::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::humanoid_monitor::VersionResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::google::protobuf::Empty, ::humanoid_monitor::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetVersion_, context, request, response);
}

void HumanoidMonitorService::Stub::async::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::humanoid_monitor::VersionResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::google::protobuf::Empty, ::humanoid_monitor::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, std::move(f));
}

void HumanoidMonitorService::Stub::async::GetVersion(::grpc::ClientContext* context, const ::google::protobuf::Empty* request, ::humanoid_monitor::VersionResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetVersion_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::humanoid_monitor::VersionResponse>* HumanoidMonitorService::Stub::PrepareAsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::humanoid_monitor::VersionResponse, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetVersion_, context, request);
}

::grpc::ClientAsyncResponseReader< ::humanoid_monitor::VersionResponse>* HumanoidMonitorService::Stub::AsyncGetVersionRaw(::grpc::ClientContext* context, const ::google::protobuf::Empty& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetVersionRaw(context, request, cq);
  result->StartCall();
  return result;
}

HumanoidMonitorService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HumanoidMonitorService_method_names[0],
      ::grpc::internal::RpcMethod::SERVER_STREAMING,
      new ::grpc::internal::ServerStreamingHandler< HumanoidMonitorService::Service, ::humanoid_monitor::SubscribeStateRequest, ::humanoid_monitor::SecurityState>(
          [](HumanoidMonitorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::humanoid_monitor::SubscribeStateRequest* req,
             ::grpc::ServerWriter<::humanoid_monitor::SecurityState>* writer) {
               return service->SubscribeState(ctx, req, writer);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HumanoidMonitorService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HumanoidMonitorService::Service, ::google::protobuf::Empty, ::humanoid_monitor::VersionResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](HumanoidMonitorService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::google::protobuf::Empty* req,
             ::humanoid_monitor::VersionResponse* resp) {
               return service->GetVersion(ctx, req, resp);
             }, this)));
}

HumanoidMonitorService::Service::~Service() {
}

::grpc::Status HumanoidMonitorService::Service::SubscribeState(::grpc::ServerContext* context, const ::humanoid_monitor::SubscribeStateRequest* request, ::grpc::ServerWriter< ::humanoid_monitor::SecurityState>* writer) {
  (void) context;
  (void) request;
  (void) writer;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status HumanoidMonitorService::Service::GetVersion(::grpc::ServerContext* context, const ::google::protobuf::Empty* request, ::humanoid_monitor::VersionResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace humanoid_monitor

