// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: joint_pos_track_err.proto
// Protobuf C++ Version: 5.29.0

#include "joint_pos_track_err.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace humanoid_monitor {
              template <typename>
PROTOBUF_CONSTEXPR SetJointPosTrackErrConfigResponse::SetJointPosTrackErrConfigResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct SetJointPosTrackErrConfigResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetJointPosTrackErrConfigResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetJointPosTrackErrConfigResponseDefaultTypeInternal() {}
  union {
    SetJointPosTrackErrConfigResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetJointPosTrackErrConfigResponseDefaultTypeInternal _SetJointPosTrackErrConfigResponse_default_instance_;

inline constexpr JointPosTrackErrParams::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : joint_index_{0},
        position_threshold_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR JointPosTrackErrParams::JointPosTrackErrParams(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct JointPosTrackErrParamsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR JointPosTrackErrParamsDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~JointPosTrackErrParamsDefaultTypeInternal() {}
  union {
    JointPosTrackErrParams _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 JointPosTrackErrParamsDefaultTypeInternal _JointPosTrackErrParams_default_instance_;
              template <typename>
PROTOBUF_CONSTEXPR GetJointPosTrackErrConfigRequest::GetJointPosTrackErrConfigRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct GetJointPosTrackErrConfigRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetJointPosTrackErrConfigRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetJointPosTrackErrConfigRequestDefaultTypeInternal() {}
  union {
    GetJointPosTrackErrConfigRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetJointPosTrackErrConfigRequestDefaultTypeInternal _GetJointPosTrackErrConfigRequest_default_instance_;

inline constexpr SetJointPosTrackErrConfigRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : params_{},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetJointPosTrackErrConfigRequest::SetJointPosTrackErrConfigRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetJointPosTrackErrConfigRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetJointPosTrackErrConfigRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetJointPosTrackErrConfigRequestDefaultTypeInternal() {}
  union {
    SetJointPosTrackErrConfigRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetJointPosTrackErrConfigRequestDefaultTypeInternal _SetJointPosTrackErrConfigRequest_default_instance_;

inline constexpr GetJointPosTrackErrConfigResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : joints_{},
        config_version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        last_updated_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetJointPosTrackErrConfigResponse::GetJointPosTrackErrConfigResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetJointPosTrackErrConfigResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetJointPosTrackErrConfigResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetJointPosTrackErrConfigResponseDefaultTypeInternal() {}
  union {
    GetJointPosTrackErrConfigResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetJointPosTrackErrConfigResponseDefaultTypeInternal _GetJointPosTrackErrConfigResponse_default_instance_;
}  // namespace humanoid_monitor
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_joint_5fpos_5ftrack_5ferr_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_joint_5fpos_5ftrack_5ferr_2eproto = nullptr;
const ::uint32_t
    TableStruct_joint_5fpos_5ftrack_5ferr_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::JointPosTrackErrParams, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::JointPosTrackErrParams, _impl_.joint_index_),
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::JointPosTrackErrParams, _impl_.position_threshold_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::SetJointPosTrackErrConfigRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::SetJointPosTrackErrConfigRequest, _impl_.params_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::SetJointPosTrackErrConfigResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::GetJointPosTrackErrConfigRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::GetJointPosTrackErrConfigResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::GetJointPosTrackErrConfigResponse, _impl_.config_version_),
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::GetJointPosTrackErrConfigResponse, _impl_.last_updated_),
        PROTOBUF_FIELD_OFFSET(::humanoid_monitor::GetJointPosTrackErrConfigResponse, _impl_.joints_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::humanoid_monitor::JointPosTrackErrParams)},
        {10, -1, -1, sizeof(::humanoid_monitor::SetJointPosTrackErrConfigRequest)},
        {19, -1, -1, sizeof(::humanoid_monitor::SetJointPosTrackErrConfigResponse)},
        {27, -1, -1, sizeof(::humanoid_monitor::GetJointPosTrackErrConfigRequest)},
        {35, -1, -1, sizeof(::humanoid_monitor::GetJointPosTrackErrConfigResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::humanoid_monitor::_JointPosTrackErrParams_default_instance_._instance,
    &::humanoid_monitor::_SetJointPosTrackErrConfigRequest_default_instance_._instance,
    &::humanoid_monitor::_SetJointPosTrackErrConfigResponse_default_instance_._instance,
    &::humanoid_monitor::_GetJointPosTrackErrConfigRequest_default_instance_._instance,
    &::humanoid_monitor::_GetJointPosTrackErrConfigResponse_default_instance_._instance,
};
const char descriptor_table_protodef_joint_5fpos_5ftrack_5ferr_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\031joint_pos_track_err.proto\022\020humanoid_mo"
    "nitor\"I\n\026JointPosTrackErrParams\022\023\n\013joint"
    "_index\030\001 \001(\005\022\032\n\022position_threshold\030\002 \001(\002"
    "\"\\\n SetJointPosTrackErrConfigRequest\0228\n\006"
    "params\030\001 \003(\0132(.humanoid_monitor.JointPos"
    "TrackErrParams\"#\n!SetJointPosTrackErrCon"
    "figResponse\"\"\n GetJointPosTrackErrConfig"
    "Request\"\213\001\n!GetJointPosTrackErrConfigRes"
    "ponse\022\026\n\016config_version\030\001 \001(\t\022\024\n\014last_up"
    "dated\030\002 \001(\t\0228\n\006joints\030\003 \003(\0132(.humanoid_m"
    "onitor.JointPosTrackErrParams2\253\002\n\027JointP"
    "osTrackErrService\022\206\001\n\031SetJointPosTrackEr"
    "rConfig\0222.humanoid_monitor.SetJointPosTr"
    "ackErrConfigRequest\0323.humanoid_monitor.S"
    "etJointPosTrackErrConfigResponse\"\000\022\206\001\n\031G"
    "etJointPosTrackErrConfig\0222.humanoid_moni"
    "tor.GetJointPosTrackErrConfigRequest\0323.h"
    "umanoid_monitor.GetJointPosTrackErrConfi"
    "gResponse\"\000b\006proto3"
};
static ::absl::once_flag descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto = {
    false,
    false,
    739,
    descriptor_table_protodef_joint_5fpos_5ftrack_5ferr_2eproto,
    "joint_pos_track_err.proto",
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto_once,
    nullptr,
    0,
    5,
    schemas,
    file_default_instances,
    TableStruct_joint_5fpos_5ftrack_5ferr_2eproto::offsets,
    file_level_enum_descriptors_joint_5fpos_5ftrack_5ferr_2eproto,
    file_level_service_descriptors_joint_5fpos_5ftrack_5ferr_2eproto,
};
namespace humanoid_monitor {
// ===================================================================

class JointPosTrackErrParams::_Internal {
 public:
};

JointPosTrackErrParams::JointPosTrackErrParams(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_monitor.JointPosTrackErrParams)
}
JointPosTrackErrParams::JointPosTrackErrParams(
    ::google::protobuf::Arena* arena, const JointPosTrackErrParams& from)
    : JointPosTrackErrParams(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE JointPosTrackErrParams::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void JointPosTrackErrParams::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, joint_index_),
           0,
           offsetof(Impl_, position_threshold_) -
               offsetof(Impl_, joint_index_) +
               sizeof(Impl_::position_threshold_));
}
JointPosTrackErrParams::~JointPosTrackErrParams() {
  // @@protoc_insertion_point(destructor:humanoid_monitor.JointPosTrackErrParams)
  SharedDtor(*this);
}
inline void JointPosTrackErrParams::SharedDtor(MessageLite& self) {
  JointPosTrackErrParams& this_ = static_cast<JointPosTrackErrParams&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* JointPosTrackErrParams::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) JointPosTrackErrParams(arena);
}
constexpr auto JointPosTrackErrParams::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(JointPosTrackErrParams),
                                            alignof(JointPosTrackErrParams));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull JointPosTrackErrParams::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_JointPosTrackErrParams_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &JointPosTrackErrParams::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<JointPosTrackErrParams>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &JointPosTrackErrParams::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<JointPosTrackErrParams>(), &JointPosTrackErrParams::ByteSizeLong,
            &JointPosTrackErrParams::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_._cached_size_),
        false,
    },
    &JointPosTrackErrParams::kDescriptorMethods,
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* JointPosTrackErrParams::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> JointPosTrackErrParams::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_monitor::JointPosTrackErrParams>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // float position_threshold = 2;
    {::_pbi::TcParser::FastF32S1,
     {21, 63, 0, PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.position_threshold_)}},
    // int32 joint_index = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(JointPosTrackErrParams, _impl_.joint_index_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.joint_index_)}},
  }}, {{
    65535, 65535
  }}, {{
    // int32 joint_index = 1;
    {PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.joint_index_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kInt32)},
    // float position_threshold = 2;
    {PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.position_threshold_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void JointPosTrackErrParams::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_monitor.JointPosTrackErrParams)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.joint_index_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.position_threshold_) -
      reinterpret_cast<char*>(&_impl_.joint_index_)) + sizeof(_impl_.position_threshold_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* JointPosTrackErrParams::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const JointPosTrackErrParams& this_ = static_cast<const JointPosTrackErrParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* JointPosTrackErrParams::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const JointPosTrackErrParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_monitor.JointPosTrackErrParams)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // int32 joint_index = 1;
          if (this_._internal_joint_index() != 0) {
            target = ::google::protobuf::internal::WireFormatLite::
                WriteInt32ToArrayWithField<1>(
                    stream, this_._internal_joint_index(), target);
          }

          // float position_threshold = 2;
          if (::absl::bit_cast<::uint32_t>(this_._internal_position_threshold()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                2, this_._internal_position_threshold(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_monitor.JointPosTrackErrParams)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t JointPosTrackErrParams::ByteSizeLong(const MessageLite& base) {
          const JointPosTrackErrParams& this_ = static_cast<const JointPosTrackErrParams&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t JointPosTrackErrParams::ByteSizeLong() const {
          const JointPosTrackErrParams& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_monitor.JointPosTrackErrParams)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // int32 joint_index = 1;
            if (this_._internal_joint_index() != 0) {
              total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
                  this_._internal_joint_index());
            }
            // float position_threshold = 2;
            if (::absl::bit_cast<::uint32_t>(this_._internal_position_threshold()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void JointPosTrackErrParams::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<JointPosTrackErrParams*>(&to_msg);
  auto& from = static_cast<const JointPosTrackErrParams&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_monitor.JointPosTrackErrParams)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_joint_index() != 0) {
    _this->_impl_.joint_index_ = from._impl_.joint_index_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_position_threshold()) != 0) {
    _this->_impl_.position_threshold_ = from._impl_.position_threshold_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void JointPosTrackErrParams::CopyFrom(const JointPosTrackErrParams& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_monitor.JointPosTrackErrParams)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void JointPosTrackErrParams::InternalSwap(JointPosTrackErrParams* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.position_threshold_)
      + sizeof(JointPosTrackErrParams::_impl_.position_threshold_)
      - PROTOBUF_FIELD_OFFSET(JointPosTrackErrParams, _impl_.joint_index_)>(
          reinterpret_cast<char*>(&_impl_.joint_index_),
          reinterpret_cast<char*>(&other->_impl_.joint_index_));
}

::google::protobuf::Metadata JointPosTrackErrParams::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetJointPosTrackErrConfigRequest::_Internal {
 public:
};

SetJointPosTrackErrConfigRequest::SetJointPosTrackErrConfigRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_monitor.SetJointPosTrackErrConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE SetJointPosTrackErrConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& from_msg)
      : params_{visibility, arena, from.params_},
        _cached_size_{0} {}

SetJointPosTrackErrConfigRequest::SetJointPosTrackErrConfigRequest(
    ::google::protobuf::Arena* arena,
    const SetJointPosTrackErrConfigRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SetJointPosTrackErrConfigRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:humanoid_monitor.SetJointPosTrackErrConfigRequest)
}
inline PROTOBUF_NDEBUG_INLINE SetJointPosTrackErrConfigRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : params_{visibility, arena},
        _cached_size_{0} {}

inline void SetJointPosTrackErrConfigRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
SetJointPosTrackErrConfigRequest::~SetJointPosTrackErrConfigRequest() {
  // @@protoc_insertion_point(destructor:humanoid_monitor.SetJointPosTrackErrConfigRequest)
  SharedDtor(*this);
}
inline void SetJointPosTrackErrConfigRequest::SharedDtor(MessageLite& self) {
  SetJointPosTrackErrConfigRequest& this_ = static_cast<SetJointPosTrackErrConfigRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SetJointPosTrackErrConfigRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SetJointPosTrackErrConfigRequest(arena);
}
constexpr auto SetJointPosTrackErrConfigRequest::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(SetJointPosTrackErrConfigRequest, _impl_.params_) +
          decltype(SetJointPosTrackErrConfigRequest::_impl_.params_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(SetJointPosTrackErrConfigRequest), alignof(SetJointPosTrackErrConfigRequest), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&SetJointPosTrackErrConfigRequest::PlacementNew_,
                                 sizeof(SetJointPosTrackErrConfigRequest),
                                 alignof(SetJointPosTrackErrConfigRequest));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SetJointPosTrackErrConfigRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SetJointPosTrackErrConfigRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SetJointPosTrackErrConfigRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SetJointPosTrackErrConfigRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SetJointPosTrackErrConfigRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SetJointPosTrackErrConfigRequest>(), &SetJointPosTrackErrConfigRequest::ByteSizeLong,
            &SetJointPosTrackErrConfigRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SetJointPosTrackErrConfigRequest, _impl_._cached_size_),
        false,
    },
    &SetJointPosTrackErrConfigRequest::kDescriptorMethods,
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SetJointPosTrackErrConfigRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2> SetJointPosTrackErrConfigRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_monitor::SetJointPosTrackErrConfigRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .humanoid_monitor.JointPosTrackErrParams params = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(SetJointPosTrackErrConfigRequest, _impl_.params_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .humanoid_monitor.JointPosTrackErrParams params = 1;
    {PROTOBUF_FIELD_OFFSET(SetJointPosTrackErrConfigRequest, _impl_.params_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::humanoid_monitor::JointPosTrackErrParams>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void SetJointPosTrackErrConfigRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_monitor.SetJointPosTrackErrConfigRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.params_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SetJointPosTrackErrConfigRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SetJointPosTrackErrConfigRequest& this_ = static_cast<const SetJointPosTrackErrConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SetJointPosTrackErrConfigRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SetJointPosTrackErrConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_monitor.SetJointPosTrackErrConfigRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // repeated .humanoid_monitor.JointPosTrackErrParams params = 1;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_params_size());
               i < n; i++) {
            const auto& repfield = this_._internal_params().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    1, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_monitor.SetJointPosTrackErrConfigRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SetJointPosTrackErrConfigRequest::ByteSizeLong(const MessageLite& base) {
          const SetJointPosTrackErrConfigRequest& this_ = static_cast<const SetJointPosTrackErrConfigRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SetJointPosTrackErrConfigRequest::ByteSizeLong() const {
          const SetJointPosTrackErrConfigRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_monitor.SetJointPosTrackErrConfigRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .humanoid_monitor.JointPosTrackErrParams params = 1;
            {
              total_size += 1UL * this_._internal_params_size();
              for (const auto& msg : this_._internal_params()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SetJointPosTrackErrConfigRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetJointPosTrackErrConfigRequest*>(&to_msg);
  auto& from = static_cast<const SetJointPosTrackErrConfigRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_monitor.SetJointPosTrackErrConfigRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_params()->MergeFrom(
      from._internal_params());
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetJointPosTrackErrConfigRequest::CopyFrom(const SetJointPosTrackErrConfigRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_monitor.SetJointPosTrackErrConfigRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetJointPosTrackErrConfigRequest::InternalSwap(SetJointPosTrackErrConfigRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.params_.InternalSwap(&other->_impl_.params_);
}

::google::protobuf::Metadata SetJointPosTrackErrConfigRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetJointPosTrackErrConfigResponse::_Internal {
 public:
};

SetJointPosTrackErrConfigResponse::SetJointPosTrackErrConfigResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:humanoid_monitor.SetJointPosTrackErrConfigResponse)
}
SetJointPosTrackErrConfigResponse::SetJointPosTrackErrConfigResponse(
    ::google::protobuf::Arena* arena,
    const SetJointPosTrackErrConfigResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SetJointPosTrackErrConfigResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:humanoid_monitor.SetJointPosTrackErrConfigResponse)
}

inline void* SetJointPosTrackErrConfigResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SetJointPosTrackErrConfigResponse(arena);
}
constexpr auto SetJointPosTrackErrConfigResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SetJointPosTrackErrConfigResponse),
                                            alignof(SetJointPosTrackErrConfigResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SetJointPosTrackErrConfigResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SetJointPosTrackErrConfigResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SetJointPosTrackErrConfigResponse::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<SetJointPosTrackErrConfigResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SetJointPosTrackErrConfigResponse::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<SetJointPosTrackErrConfigResponse>(), &SetJointPosTrackErrConfigResponse::ByteSizeLong,
            &SetJointPosTrackErrConfigResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SetJointPosTrackErrConfigResponse, _impl_._cached_size_),
        false,
    },
    &SetJointPosTrackErrConfigResponse::kDescriptorMethods,
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SetJointPosTrackErrConfigResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> SetJointPosTrackErrConfigResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_monitor::SetJointPosTrackErrConfigResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata SetJointPosTrackErrConfigResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetJointPosTrackErrConfigRequest::_Internal {
 public:
};

GetJointPosTrackErrConfigRequest::GetJointPosTrackErrConfigRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:humanoid_monitor.GetJointPosTrackErrConfigRequest)
}
GetJointPosTrackErrConfigRequest::GetJointPosTrackErrConfigRequest(
    ::google::protobuf::Arena* arena,
    const GetJointPosTrackErrConfigRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetJointPosTrackErrConfigRequest* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:humanoid_monitor.GetJointPosTrackErrConfigRequest)
}

inline void* GetJointPosTrackErrConfigRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetJointPosTrackErrConfigRequest(arena);
}
constexpr auto GetJointPosTrackErrConfigRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetJointPosTrackErrConfigRequest),
                                            alignof(GetJointPosTrackErrConfigRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetJointPosTrackErrConfigRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetJointPosTrackErrConfigRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetJointPosTrackErrConfigRequest::MergeImpl,
        ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<GetJointPosTrackErrConfigRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetJointPosTrackErrConfigRequest::SharedDtor,
        ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<GetJointPosTrackErrConfigRequest>(), &GetJointPosTrackErrConfigRequest::ByteSizeLong,
            &GetJointPosTrackErrConfigRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigRequest, _impl_._cached_size_),
        false,
    },
    &GetJointPosTrackErrConfigRequest::kDescriptorMethods,
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetJointPosTrackErrConfigRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2> GetJointPosTrackErrConfigRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_monitor::GetJointPosTrackErrConfigRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }},
  // no field_entries, or aux_entries
  {{
  }},
};








::google::protobuf::Metadata GetJointPosTrackErrConfigRequest::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class GetJointPosTrackErrConfigResponse::_Internal {
 public:
};

GetJointPosTrackErrConfigResponse::GetJointPosTrackErrConfigResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:humanoid_monitor.GetJointPosTrackErrConfigResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetJointPosTrackErrConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::humanoid_monitor::GetJointPosTrackErrConfigResponse& from_msg)
      : joints_{visibility, arena, from.joints_},
        config_version_(arena, from.config_version_),
        last_updated_(arena, from.last_updated_),
        _cached_size_{0} {}

GetJointPosTrackErrConfigResponse::GetJointPosTrackErrConfigResponse(
    ::google::protobuf::Arena* arena,
    const GetJointPosTrackErrConfigResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  GetJointPosTrackErrConfigResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:humanoid_monitor.GetJointPosTrackErrConfigResponse)
}
inline PROTOBUF_NDEBUG_INLINE GetJointPosTrackErrConfigResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : joints_{visibility, arena},
        config_version_(arena),
        last_updated_(arena),
        _cached_size_{0} {}

inline void GetJointPosTrackErrConfigResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
GetJointPosTrackErrConfigResponse::~GetJointPosTrackErrConfigResponse() {
  // @@protoc_insertion_point(destructor:humanoid_monitor.GetJointPosTrackErrConfigResponse)
  SharedDtor(*this);
}
inline void GetJointPosTrackErrConfigResponse::SharedDtor(MessageLite& self) {
  GetJointPosTrackErrConfigResponse& this_ = static_cast<GetJointPosTrackErrConfigResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.config_version_.Destroy();
  this_._impl_.last_updated_.Destroy();
  this_._impl_.~Impl_();
}

inline void* GetJointPosTrackErrConfigResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetJointPosTrackErrConfigResponse(arena);
}
constexpr auto GetJointPosTrackErrConfigResponse::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.joints_) +
          decltype(GetJointPosTrackErrConfigResponse::_impl_.joints_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(GetJointPosTrackErrConfigResponse), alignof(GetJointPosTrackErrConfigResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&GetJointPosTrackErrConfigResponse::PlacementNew_,
                                 sizeof(GetJointPosTrackErrConfigResponse),
                                 alignof(GetJointPosTrackErrConfigResponse));
  }
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetJointPosTrackErrConfigResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetJointPosTrackErrConfigResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetJointPosTrackErrConfigResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetJointPosTrackErrConfigResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetJointPosTrackErrConfigResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetJointPosTrackErrConfigResponse>(), &GetJointPosTrackErrConfigResponse::ByteSizeLong,
            &GetJointPosTrackErrConfigResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_._cached_size_),
        false,
    },
    &GetJointPosTrackErrConfigResponse::kDescriptorMethods,
    &descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetJointPosTrackErrConfigResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 85, 2> GetJointPosTrackErrConfigResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::humanoid_monitor::GetJointPosTrackErrConfigResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string config_version = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.config_version_)}},
    // string last_updated = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.last_updated_)}},
    // repeated .humanoid_monitor.JointPosTrackErrParams joints = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.joints_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string config_version = 1;
    {PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.config_version_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string last_updated = 2;
    {PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.last_updated_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // repeated .humanoid_monitor.JointPosTrackErrParams joints = 3;
    {PROTOBUF_FIELD_OFFSET(GetJointPosTrackErrConfigResponse, _impl_.joints_), 0, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::humanoid_monitor::JointPosTrackErrParams>()},
  }}, {{
    "\62\16\14\0\0\0\0\0"
    "humanoid_monitor.GetJointPosTrackErrConfigResponse"
    "config_version"
    "last_updated"
  }},
};

PROTOBUF_NOINLINE void GetJointPosTrackErrConfigResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:humanoid_monitor.GetJointPosTrackErrConfigResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.joints_.Clear();
  _impl_.config_version_.ClearToEmpty();
  _impl_.last_updated_.ClearToEmpty();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetJointPosTrackErrConfigResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetJointPosTrackErrConfigResponse& this_ = static_cast<const GetJointPosTrackErrConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetJointPosTrackErrConfigResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetJointPosTrackErrConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:humanoid_monitor.GetJointPosTrackErrConfigResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string config_version = 1;
          if (!this_._internal_config_version().empty()) {
            const std::string& _s = this_._internal_config_version();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "humanoid_monitor.GetJointPosTrackErrConfigResponse.config_version");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // string last_updated = 2;
          if (!this_._internal_last_updated().empty()) {
            const std::string& _s = this_._internal_last_updated();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "humanoid_monitor.GetJointPosTrackErrConfigResponse.last_updated");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // repeated .humanoid_monitor.JointPosTrackErrParams joints = 3;
          for (unsigned i = 0, n = static_cast<unsigned>(
                                   this_._internal_joints_size());
               i < n; i++) {
            const auto& repfield = this_._internal_joints().Get(i);
            target =
                ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                    3, repfield, repfield.GetCachedSize(),
                    target, stream);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:humanoid_monitor.GetJointPosTrackErrConfigResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetJointPosTrackErrConfigResponse::ByteSizeLong(const MessageLite& base) {
          const GetJointPosTrackErrConfigResponse& this_ = static_cast<const GetJointPosTrackErrConfigResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetJointPosTrackErrConfigResponse::ByteSizeLong() const {
          const GetJointPosTrackErrConfigResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:humanoid_monitor.GetJointPosTrackErrConfigResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // repeated .humanoid_monitor.JointPosTrackErrParams joints = 3;
            {
              total_size += 1UL * this_._internal_joints_size();
              for (const auto& msg : this_._internal_joints()) {
                total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
              }
            }
          }
           {
            // string config_version = 1;
            if (!this_._internal_config_version().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_config_version());
            }
            // string last_updated = 2;
            if (!this_._internal_last_updated().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_last_updated());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetJointPosTrackErrConfigResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetJointPosTrackErrConfigResponse*>(&to_msg);
  auto& from = static_cast<const GetJointPosTrackErrConfigResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:humanoid_monitor.GetJointPosTrackErrConfigResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_joints()->MergeFrom(
      from._internal_joints());
  if (!from._internal_config_version().empty()) {
    _this->_internal_set_config_version(from._internal_config_version());
  }
  if (!from._internal_last_updated().empty()) {
    _this->_internal_set_last_updated(from._internal_last_updated());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetJointPosTrackErrConfigResponse::CopyFrom(const GetJointPosTrackErrConfigResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:humanoid_monitor.GetJointPosTrackErrConfigResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetJointPosTrackErrConfigResponse::InternalSwap(GetJointPosTrackErrConfigResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.joints_.InternalSwap(&other->_impl_.joints_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.config_version_, &other->_impl_.config_version_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.last_updated_, &other->_impl_.last_updated_, arena);
}

::google::protobuf::Metadata GetJointPosTrackErrConfigResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace humanoid_monitor
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_joint_5fpos_5ftrack_5ferr_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
