// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: joint_speed_check.proto
#ifndef GRPC_joint_5fspeed_5fcheck_2eproto__INCLUDED
#define GRPC_joint_5fspeed_5fcheck_2eproto__INCLUDED

#include "joint_speed_check.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace humanoid_monitor {

class JointSpeedCheckService final {
 public:
  static constexpr char const* service_full_name() {
    return "humanoid_monitor.JointSpeedCheckService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>> AsyncSetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>>(AsyncSetJointSpeedCheckConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>> PrepareAsyncSetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>>(PrepareAsyncSetJointSpeedCheckConfigRaw(context, request, cq));
    }
    virtual ::grpc::Status GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>> AsyncGetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>>(AsyncGetJointSpeedCheckConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>> PrepareAsyncGetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>>(PrepareAsyncGetJointSpeedCheckConfigRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* AsyncSetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* PrepareAsyncSetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* AsyncGetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* PrepareAsyncGetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>> AsyncSetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>>(AsyncSetJointSpeedCheckConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>> PrepareAsyncSetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>>(PrepareAsyncSetJointSpeedCheckConfigRaw(context, request, cq));
    }
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>> AsyncGetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>>(AsyncGetJointSpeedCheckConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>> PrepareAsyncGetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>>(PrepareAsyncGetJointSpeedCheckConfigRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void SetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void GetJointSpeedCheckConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* AsyncSetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* PrepareAsyncSetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* AsyncGetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* PrepareAsyncGetJointSpeedCheckConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetJointSpeedCheckConfig_;
    const ::grpc::internal::RpcMethod rpcmethod_GetJointSpeedCheckConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response);
    virtual ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetJointSpeedCheckConfig(::grpc::ServerContext* context, ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetJointSpeedCheckConfig(::grpc::ServerContext* context, ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetJointSpeedCheckConfig<WithAsyncMethod_GetJointSpeedCheckConfig<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::SetJointSpeedCheckConfigRequest, ::humanoid_monitor::SetJointSpeedCheckConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* response) { return this->SetJointSpeedCheckConfig(context, request, response); }));}
    void SetMessageAllocatorFor_SetJointSpeedCheckConfig(
        ::grpc::MessageAllocator< ::humanoid_monitor::SetJointSpeedCheckConfigRequest, ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::SetJointSpeedCheckConfigRequest, ::humanoid_monitor::SetJointSpeedCheckConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetJointSpeedCheckConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::GetJointSpeedCheckConfigRequest, ::humanoid_monitor::GetJointSpeedCheckConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* request, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* response) { return this->GetJointSpeedCheckConfig(context, request, response); }));}
    void SetMessageAllocatorFor_GetJointSpeedCheckConfig(
        ::grpc::MessageAllocator< ::humanoid_monitor::GetJointSpeedCheckConfigRequest, ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::GetJointSpeedCheckConfigRequest, ::humanoid_monitor::GetJointSpeedCheckConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetJointSpeedCheckConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetJointSpeedCheckConfig<WithCallbackMethod_GetJointSpeedCheckConfig<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetJointSpeedCheckConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetJointSpeedCheckConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetJointSpeedCheckConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetJointSpeedCheckConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetJointSpeedCheckConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetJointSpeedCheckConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::humanoid_monitor::SetJointSpeedCheckConfigRequest, ::humanoid_monitor::SetJointSpeedCheckConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::humanoid_monitor::SetJointSpeedCheckConfigRequest, ::humanoid_monitor::SetJointSpeedCheckConfigResponse>* streamer) {
                       return this->StreamedSetJointSpeedCheckConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::SetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetJointSpeedCheckConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::humanoid_monitor::SetJointSpeedCheckConfigRequest,::humanoid_monitor::SetJointSpeedCheckConfigResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetJointSpeedCheckConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetJointSpeedCheckConfig() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::humanoid_monitor::GetJointSpeedCheckConfigRequest, ::humanoid_monitor::GetJointSpeedCheckConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::humanoid_monitor::GetJointSpeedCheckConfigRequest, ::humanoid_monitor::GetJointSpeedCheckConfigResponse>* streamer) {
                       return this->StreamedGetJointSpeedCheckConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetJointSpeedCheckConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetJointSpeedCheckConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointSpeedCheckConfigRequest* /*request*/, ::humanoid_monitor::GetJointSpeedCheckConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetJointSpeedCheckConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::humanoid_monitor::GetJointSpeedCheckConfigRequest,::humanoid_monitor::GetJointSpeedCheckConfigResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetJointSpeedCheckConfig<WithStreamedUnaryMethod_GetJointSpeedCheckConfig<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetJointSpeedCheckConfig<WithStreamedUnaryMethod_GetJointSpeedCheckConfig<Service > > StreamedService;
};

}  // namespace humanoid_monitor


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_joint_5fspeed_5fcheck_2eproto__INCLUDED
