// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: joint_pos_track_err.proto
#ifndef GRPC_joint_5fpos_5ftrack_5ferr_2eproto__INCLUDED
#define GRPC_joint_5fpos_5ftrack_5ferr_2eproto__INCLUDED

#include "joint_pos_track_err.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace humanoid_monitor {

class JointPosTrackErrService final {
 public:
  static constexpr char const* service_full_name() {
    return "humanoid_monitor.JointPosTrackErrService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>> AsyncSetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>>(AsyncSetJointPosTrackErrConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>> PrepareAsyncSetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>>(PrepareAsyncSetJointPosTrackErrConfigRaw(context, request, cq));
    }
    virtual ::grpc::Status GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>> AsyncGetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>>(AsyncGetJointPosTrackErrConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>> PrepareAsyncGetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>>(PrepareAsyncGetJointPosTrackErrConfigRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* AsyncSetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* PrepareAsyncSetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* AsyncGetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* PrepareAsyncGetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>> AsyncSetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>>(AsyncSetJointPosTrackErrConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>> PrepareAsyncSetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>>(PrepareAsyncSetJointPosTrackErrConfigRaw(context, request, cq));
    }
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>> AsyncGetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>>(AsyncGetJointPosTrackErrConfigRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>> PrepareAsyncGetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>>(PrepareAsyncGetJointPosTrackErrConfigRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void SetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response, std::function<void(::grpc::Status)>) override;
      void GetJointPosTrackErrConfig(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* AsyncSetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* PrepareAsyncSetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* AsyncGetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* PrepareAsyncGetJointPosTrackErrConfigRaw(::grpc::ClientContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetJointPosTrackErrConfig_;
    const ::grpc::internal::RpcMethod rpcmethod_GetJointPosTrackErrConfig_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response);
    virtual ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetJointPosTrackErrConfig(::grpc::ServerContext* context, ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetJointPosTrackErrConfig(::grpc::ServerContext* context, ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::grpc::ServerAsyncResponseWriter< ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetJointPosTrackErrConfig<WithAsyncMethod_GetJointPosTrackErrConfig<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::SetJointPosTrackErrConfigRequest, ::humanoid_monitor::SetJointPosTrackErrConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* response) { return this->SetJointPosTrackErrConfig(context, request, response); }));}
    void SetMessageAllocatorFor_SetJointPosTrackErrConfig(
        ::grpc::MessageAllocator< ::humanoid_monitor::SetJointPosTrackErrConfigRequest, ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::SetJointPosTrackErrConfigRequest, ::humanoid_monitor::SetJointPosTrackErrConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetJointPosTrackErrConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::GetJointPosTrackErrConfigRequest, ::humanoid_monitor::GetJointPosTrackErrConfigResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* request, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* response) { return this->GetJointPosTrackErrConfig(context, request, response); }));}
    void SetMessageAllocatorFor_GetJointPosTrackErrConfig(
        ::grpc::MessageAllocator< ::humanoid_monitor::GetJointPosTrackErrConfigRequest, ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::humanoid_monitor::GetJointPosTrackErrConfigRequest, ::humanoid_monitor::GetJointPosTrackErrConfigResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetJointPosTrackErrConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_SetJointPosTrackErrConfig<WithCallbackMethod_GetJointPosTrackErrConfig<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetJointPosTrackErrConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetJointPosTrackErrConfig(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetJointPosTrackErrConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* SetJointPosTrackErrConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetJointPosTrackErrConfig(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetJointPosTrackErrConfig(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::humanoid_monitor::SetJointPosTrackErrConfigRequest, ::humanoid_monitor::SetJointPosTrackErrConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::humanoid_monitor::SetJointPosTrackErrConfigRequest, ::humanoid_monitor::SetJointPosTrackErrConfigResponse>* streamer) {
                       return this->StreamedSetJointPosTrackErrConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::SetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::SetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetJointPosTrackErrConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::humanoid_monitor::SetJointPosTrackErrConfigRequest,::humanoid_monitor::SetJointPosTrackErrConfigResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetJointPosTrackErrConfig : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetJointPosTrackErrConfig() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::humanoid_monitor::GetJointPosTrackErrConfigRequest, ::humanoid_monitor::GetJointPosTrackErrConfigResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::humanoid_monitor::GetJointPosTrackErrConfigRequest, ::humanoid_monitor::GetJointPosTrackErrConfigResponse>* streamer) {
                       return this->StreamedGetJointPosTrackErrConfig(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetJointPosTrackErrConfig() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetJointPosTrackErrConfig(::grpc::ServerContext* /*context*/, const ::humanoid_monitor::GetJointPosTrackErrConfigRequest* /*request*/, ::humanoid_monitor::GetJointPosTrackErrConfigResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetJointPosTrackErrConfig(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::humanoid_monitor::GetJointPosTrackErrConfigRequest,::humanoid_monitor::GetJointPosTrackErrConfigResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetJointPosTrackErrConfig<WithStreamedUnaryMethod_GetJointPosTrackErrConfig<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetJointPosTrackErrConfig<WithStreamedUnaryMethod_GetJointPosTrackErrConfig<Service > > StreamedService;
};

}  // namespace humanoid_monitor


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_joint_5fpos_5ftrack_5ferr_2eproto__INCLUDED
