// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: chassis_service.proto
// Protobuf C++ Version: 5.29.0

#include "chassis_service.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace controller {

inline constexpr SetMaxVelocityResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : success_{false},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetMaxVelocityResponse::SetMaxVelocityResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetMaxVelocityResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetMaxVelocityResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetMaxVelocityResponseDefaultTypeInternal() {}
  union {
    SetMaxVelocityResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetMaxVelocityResponseDefaultTypeInternal _SetMaxVelocityResponse_default_instance_;

inline constexpr SetMaxVelocityRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : linear_velocity_{0},
        angular_velocity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR SetMaxVelocityRequest::SetMaxVelocityRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct SetMaxVelocityRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR SetMaxVelocityRequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~SetMaxVelocityRequestDefaultTypeInternal() {}
  union {
    SetMaxVelocityRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 SetMaxVelocityRequestDefaultTypeInternal _SetMaxVelocityRequest_default_instance_;

inline constexpr GetMaxVelocityResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : linear_velocity_{0},
        angular_velocity_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR GetMaxVelocityResponse::GetMaxVelocityResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct GetMaxVelocityResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR GetMaxVelocityResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~GetMaxVelocityResponseDefaultTypeInternal() {}
  union {
    GetMaxVelocityResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 GetMaxVelocityResponseDefaultTypeInternal _GetMaxVelocityResponse_default_instance_;
}  // namespace controller
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_chassis_5fservice_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_chassis_5fservice_2eproto = nullptr;
const ::uint32_t
    TableStruct_chassis_5fservice_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::GetMaxVelocityResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::GetMaxVelocityResponse, _impl_.linear_velocity_),
        PROTOBUF_FIELD_OFFSET(::controller::GetMaxVelocityResponse, _impl_.angular_velocity_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::SetMaxVelocityRequest, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::SetMaxVelocityRequest, _impl_.linear_velocity_),
        PROTOBUF_FIELD_OFFSET(::controller::SetMaxVelocityRequest, _impl_.angular_velocity_),
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::controller::SetMaxVelocityResponse, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::controller::SetMaxVelocityResponse, _impl_.success_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::controller::GetMaxVelocityResponse)},
        {10, -1, -1, sizeof(::controller::SetMaxVelocityRequest)},
        {20, -1, -1, sizeof(::controller::SetMaxVelocityResponse)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::controller::_GetMaxVelocityResponse_default_instance_._instance,
    &::controller::_SetMaxVelocityRequest_default_instance_._instance,
    &::controller::_SetMaxVelocityResponse_default_instance_._instance,
};
const char descriptor_table_protodef_chassis_5fservice_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\025chassis_service.proto\022\ncontroller\032\033goo"
    "gle/protobuf/empty.proto\"K\n\026GetMaxVeloci"
    "tyResponse\022\027\n\017linear_velocity\030\001 \001(\001\022\030\n\020a"
    "ngular_velocity\030\002 \001(\001\"J\n\025SetMaxVelocityR"
    "equest\022\027\n\017linear_velocity\030\001 \001(\001\022\030\n\020angul"
    "ar_velocity\030\002 \001(\001\")\n\026SetMaxVelocityRespo"
    "nse\022\017\n\007success\030\001 \001(\0102\311\001\n\016ClassisService\022"
    "`\n\025RequestSetMaxVelocity\022!.controller.Se"
    "tMaxVelocityRequest\032\".controller.SetMaxV"
    "elocityResponse\"\000\022U\n\025RequestGetMaxVeloci"
    "ty\022\026.google.protobuf.Empty\032\".controller."
    "GetMaxVelocityResponse\"\000b\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_chassis_5fservice_2eproto_deps[1] =
    {
        &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
};
static ::absl::once_flag descriptor_table_chassis_5fservice_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_chassis_5fservice_2eproto = {
    false,
    false,
    472,
    descriptor_table_protodef_chassis_5fservice_2eproto,
    "chassis_service.proto",
    &descriptor_table_chassis_5fservice_2eproto_once,
    descriptor_table_chassis_5fservice_2eproto_deps,
    1,
    3,
    schemas,
    file_default_instances,
    TableStruct_chassis_5fservice_2eproto::offsets,
    file_level_enum_descriptors_chassis_5fservice_2eproto,
    file_level_service_descriptors_chassis_5fservice_2eproto,
};
namespace controller {
// ===================================================================

class GetMaxVelocityResponse::_Internal {
 public:
};

GetMaxVelocityResponse::GetMaxVelocityResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.GetMaxVelocityResponse)
}
GetMaxVelocityResponse::GetMaxVelocityResponse(
    ::google::protobuf::Arena* arena, const GetMaxVelocityResponse& from)
    : GetMaxVelocityResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE GetMaxVelocityResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void GetMaxVelocityResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, linear_velocity_),
           0,
           offsetof(Impl_, angular_velocity_) -
               offsetof(Impl_, linear_velocity_) +
               sizeof(Impl_::angular_velocity_));
}
GetMaxVelocityResponse::~GetMaxVelocityResponse() {
  // @@protoc_insertion_point(destructor:controller.GetMaxVelocityResponse)
  SharedDtor(*this);
}
inline void GetMaxVelocityResponse::SharedDtor(MessageLite& self) {
  GetMaxVelocityResponse& this_ = static_cast<GetMaxVelocityResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* GetMaxVelocityResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) GetMaxVelocityResponse(arena);
}
constexpr auto GetMaxVelocityResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(GetMaxVelocityResponse),
                                            alignof(GetMaxVelocityResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull GetMaxVelocityResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_GetMaxVelocityResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &GetMaxVelocityResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<GetMaxVelocityResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &GetMaxVelocityResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<GetMaxVelocityResponse>(), &GetMaxVelocityResponse::ByteSizeLong,
            &GetMaxVelocityResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_._cached_size_),
        false,
    },
    &GetMaxVelocityResponse::kDescriptorMethods,
    &descriptor_table_chassis_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* GetMaxVelocityResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> GetMaxVelocityResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::GetMaxVelocityResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double angular_velocity = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.angular_velocity_)}},
    // double linear_velocity = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.linear_velocity_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double linear_velocity = 1;
    {PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.linear_velocity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double angular_velocity = 2;
    {PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.angular_velocity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void GetMaxVelocityResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.GetMaxVelocityResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.linear_velocity_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.angular_velocity_) -
      reinterpret_cast<char*>(&_impl_.linear_velocity_)) + sizeof(_impl_.angular_velocity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* GetMaxVelocityResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const GetMaxVelocityResponse& this_ = static_cast<const GetMaxVelocityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* GetMaxVelocityResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const GetMaxVelocityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.GetMaxVelocityResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double linear_velocity = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_linear_velocity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_linear_velocity(), target);
          }

          // double angular_velocity = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_angular_velocity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_angular_velocity(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.GetMaxVelocityResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t GetMaxVelocityResponse::ByteSizeLong(const MessageLite& base) {
          const GetMaxVelocityResponse& this_ = static_cast<const GetMaxVelocityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t GetMaxVelocityResponse::ByteSizeLong() const {
          const GetMaxVelocityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.GetMaxVelocityResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double linear_velocity = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_linear_velocity()) != 0) {
              total_size += 9;
            }
            // double angular_velocity = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_angular_velocity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void GetMaxVelocityResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<GetMaxVelocityResponse*>(&to_msg);
  auto& from = static_cast<const GetMaxVelocityResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.GetMaxVelocityResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_linear_velocity()) != 0) {
    _this->_impl_.linear_velocity_ = from._impl_.linear_velocity_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_angular_velocity()) != 0) {
    _this->_impl_.angular_velocity_ = from._impl_.angular_velocity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void GetMaxVelocityResponse::CopyFrom(const GetMaxVelocityResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.GetMaxVelocityResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void GetMaxVelocityResponse::InternalSwap(GetMaxVelocityResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.angular_velocity_)
      + sizeof(GetMaxVelocityResponse::_impl_.angular_velocity_)
      - PROTOBUF_FIELD_OFFSET(GetMaxVelocityResponse, _impl_.linear_velocity_)>(
          reinterpret_cast<char*>(&_impl_.linear_velocity_),
          reinterpret_cast<char*>(&other->_impl_.linear_velocity_));
}

::google::protobuf::Metadata GetMaxVelocityResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetMaxVelocityRequest::_Internal {
 public:
};

SetMaxVelocityRequest::SetMaxVelocityRequest(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.SetMaxVelocityRequest)
}
SetMaxVelocityRequest::SetMaxVelocityRequest(
    ::google::protobuf::Arena* arena, const SetMaxVelocityRequest& from)
    : SetMaxVelocityRequest(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SetMaxVelocityRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SetMaxVelocityRequest::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, linear_velocity_),
           0,
           offsetof(Impl_, angular_velocity_) -
               offsetof(Impl_, linear_velocity_) +
               sizeof(Impl_::angular_velocity_));
}
SetMaxVelocityRequest::~SetMaxVelocityRequest() {
  // @@protoc_insertion_point(destructor:controller.SetMaxVelocityRequest)
  SharedDtor(*this);
}
inline void SetMaxVelocityRequest::SharedDtor(MessageLite& self) {
  SetMaxVelocityRequest& this_ = static_cast<SetMaxVelocityRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SetMaxVelocityRequest::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SetMaxVelocityRequest(arena);
}
constexpr auto SetMaxVelocityRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SetMaxVelocityRequest),
                                            alignof(SetMaxVelocityRequest));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SetMaxVelocityRequest::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SetMaxVelocityRequest_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SetMaxVelocityRequest::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SetMaxVelocityRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SetMaxVelocityRequest::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SetMaxVelocityRequest>(), &SetMaxVelocityRequest::ByteSizeLong,
            &SetMaxVelocityRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_._cached_size_),
        false,
    },
    &SetMaxVelocityRequest::kDescriptorMethods,
    &descriptor_table_chassis_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SetMaxVelocityRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<1, 2, 0, 0, 2> SetMaxVelocityRequest::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    2, 8,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967292,  // skipmap
    offsetof(decltype(_table_), field_entries),
    2,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::SetMaxVelocityRequest>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // double angular_velocity = 2;
    {::_pbi::TcParser::FastF64S1,
     {17, 63, 0, PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.angular_velocity_)}},
    // double linear_velocity = 1;
    {::_pbi::TcParser::FastF64S1,
     {9, 63, 0, PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.linear_velocity_)}},
  }}, {{
    65535, 65535
  }}, {{
    // double linear_velocity = 1;
    {PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.linear_velocity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
    // double angular_velocity = 2;
    {PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.angular_velocity_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kDouble)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SetMaxVelocityRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.SetMaxVelocityRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&_impl_.linear_velocity_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.angular_velocity_) -
      reinterpret_cast<char*>(&_impl_.linear_velocity_)) + sizeof(_impl_.angular_velocity_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SetMaxVelocityRequest::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SetMaxVelocityRequest& this_ = static_cast<const SetMaxVelocityRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SetMaxVelocityRequest::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SetMaxVelocityRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.SetMaxVelocityRequest)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // double linear_velocity = 1;
          if (::absl::bit_cast<::uint64_t>(this_._internal_linear_velocity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                1, this_._internal_linear_velocity(), target);
          }

          // double angular_velocity = 2;
          if (::absl::bit_cast<::uint64_t>(this_._internal_angular_velocity()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteDoubleToArray(
                2, this_._internal_angular_velocity(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.SetMaxVelocityRequest)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SetMaxVelocityRequest::ByteSizeLong(const MessageLite& base) {
          const SetMaxVelocityRequest& this_ = static_cast<const SetMaxVelocityRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SetMaxVelocityRequest::ByteSizeLong() const {
          const SetMaxVelocityRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.SetMaxVelocityRequest)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // double linear_velocity = 1;
            if (::absl::bit_cast<::uint64_t>(this_._internal_linear_velocity()) != 0) {
              total_size += 9;
            }
            // double angular_velocity = 2;
            if (::absl::bit_cast<::uint64_t>(this_._internal_angular_velocity()) != 0) {
              total_size += 9;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SetMaxVelocityRequest::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetMaxVelocityRequest*>(&to_msg);
  auto& from = static_cast<const SetMaxVelocityRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.SetMaxVelocityRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (::absl::bit_cast<::uint64_t>(from._internal_linear_velocity()) != 0) {
    _this->_impl_.linear_velocity_ = from._impl_.linear_velocity_;
  }
  if (::absl::bit_cast<::uint64_t>(from._internal_angular_velocity()) != 0) {
    _this->_impl_.angular_velocity_ = from._impl_.angular_velocity_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetMaxVelocityRequest::CopyFrom(const SetMaxVelocityRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.SetMaxVelocityRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetMaxVelocityRequest::InternalSwap(SetMaxVelocityRequest* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.angular_velocity_)
      + sizeof(SetMaxVelocityRequest::_impl_.angular_velocity_)
      - PROTOBUF_FIELD_OFFSET(SetMaxVelocityRequest, _impl_.linear_velocity_)>(
          reinterpret_cast<char*>(&_impl_.linear_velocity_),
          reinterpret_cast<char*>(&other->_impl_.linear_velocity_));
}

::google::protobuf::Metadata SetMaxVelocityRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class SetMaxVelocityResponse::_Internal {
 public:
};

SetMaxVelocityResponse::SetMaxVelocityResponse(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:controller.SetMaxVelocityResponse)
}
SetMaxVelocityResponse::SetMaxVelocityResponse(
    ::google::protobuf::Arena* arena, const SetMaxVelocityResponse& from)
    : SetMaxVelocityResponse(arena) {
  MergeFrom(from);
}
inline PROTOBUF_NDEBUG_INLINE SetMaxVelocityResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void SetMaxVelocityResponse::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.success_ = {};
}
SetMaxVelocityResponse::~SetMaxVelocityResponse() {
  // @@protoc_insertion_point(destructor:controller.SetMaxVelocityResponse)
  SharedDtor(*this);
}
inline void SetMaxVelocityResponse::SharedDtor(MessageLite& self) {
  SetMaxVelocityResponse& this_ = static_cast<SetMaxVelocityResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* SetMaxVelocityResponse::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) SetMaxVelocityResponse(arena);
}
constexpr auto SetMaxVelocityResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(SetMaxVelocityResponse),
                                            alignof(SetMaxVelocityResponse));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull SetMaxVelocityResponse::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_SetMaxVelocityResponse_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &SetMaxVelocityResponse::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<SetMaxVelocityResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &SetMaxVelocityResponse::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<SetMaxVelocityResponse>(), &SetMaxVelocityResponse::ByteSizeLong,
            &SetMaxVelocityResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(SetMaxVelocityResponse, _impl_._cached_size_),
        false,
    },
    &SetMaxVelocityResponse::kDescriptorMethods,
    &descriptor_table_chassis_5fservice_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* SetMaxVelocityResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2> SetMaxVelocityResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::controller::SetMaxVelocityResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // bool success = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(SetMaxVelocityResponse, _impl_.success_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(SetMaxVelocityResponse, _impl_.success_)}},
  }}, {{
    65535, 65535
  }}, {{
    // bool success = 1;
    {PROTOBUF_FIELD_OFFSET(SetMaxVelocityResponse, _impl_.success_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};

PROTOBUF_NOINLINE void SetMaxVelocityResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:controller.SetMaxVelocityResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.success_ = false;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* SetMaxVelocityResponse::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const SetMaxVelocityResponse& this_ = static_cast<const SetMaxVelocityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* SetMaxVelocityResponse::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const SetMaxVelocityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:controller.SetMaxVelocityResponse)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // bool success = 1;
          if (this_._internal_success() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteBoolToArray(
                1, this_._internal_success(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:controller.SetMaxVelocityResponse)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t SetMaxVelocityResponse::ByteSizeLong(const MessageLite& base) {
          const SetMaxVelocityResponse& this_ = static_cast<const SetMaxVelocityResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t SetMaxVelocityResponse::ByteSizeLong() const {
          const SetMaxVelocityResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:controller.SetMaxVelocityResponse)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

           {
            // bool success = 1;
            if (this_._internal_success() != 0) {
              total_size += 2;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void SetMaxVelocityResponse::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<SetMaxVelocityResponse*>(&to_msg);
  auto& from = static_cast<const SetMaxVelocityResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:controller.SetMaxVelocityResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (from._internal_success() != 0) {
    _this->_impl_.success_ = from._impl_.success_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void SetMaxVelocityResponse::CopyFrom(const SetMaxVelocityResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:controller.SetMaxVelocityResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void SetMaxVelocityResponse::InternalSwap(SetMaxVelocityResponse* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
        swap(_impl_.success_, other->_impl_.success_);
}

::google::protobuf::Metadata SetMaxVelocityResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace controller
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_chassis_5fservice_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
